syntax = "proto3";

package spaceship.v1;

option go_package = "grpc-practice/pkg/proto/spaceship/v1;spaceship_v1";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "validate/validate.proto";
import "google/api/annotations.proto";

service SpaceshipServiceV1{
  rpc Create(CreateRequest) returns (CreateResponse){
    option (google.api.http) = {
      post: "/api/v1/spaceship"
      body: "*"
    };
  };

  rpc Get(GetRequest) returns (GetResponse){
    option (google.api.http) = {
      get: "/api/v1/spaceship/{uuid}"
    };
  };

  rpc Update(UpdateRequest) returns (UpdateResponse){
    option (google.api.http) = {
      patch: "/api/v1/spaceship/{uuid}"
      body: "*"
    };
  };

  rpc Delete(DeleteRequest) returns (google.protobuf.Empty){
    option (google.api.http) = {
      delete: "/api/v1/spaceship/{uuid}"
    };
  };
}

message SpaceshipInfo{
  string name = 1 [(validate.rules).string = {min_len: 3, max_len: 50}];

  google.protobuf.StringValue description = 2;

  string model = 3;

  string manufacturer = 4;

  double price = 5;
}

message SpaceshipUpdateInfo{
  google.protobuf.StringValue name = 1;

  google.protobuf.StringValue description = 2;

  google.protobuf.StringValue model = 3;

  google.protobuf.StringValue manufacturer = 4;

  google.protobuf.DoubleValue price = 5;
}

message Spaceship{
  string uuid = 1;

  SpaceshipInfo info = 2;

  google.protobuf.Timestamp created_at = 3;

  google.protobuf.Timestamp updated_at = 4;
}

message CreateRequest{
  SpaceshipInfo info = 1;
}

message CreateResponse{
  Spaceship spaceship = 1;
}

message GetRequest{
  string uuid = 1;
}

message GetResponse{
  Spaceship spaceship = 1;
}

message UpdateRequest{
  string uuid = 1;
  SpaceshipUpdateInfo update_info = 2;
}

message UpdateResponse{
  Spaceship spaceship = 1;
}

message DeleteRequest{
  string uuid = 1;
}