// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/spaceship/v1/spaceship.proto

package spaceship_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceshipInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Model         string                  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer  string                  `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Price         float64                 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceshipInfo) Reset() {
	*x = SpaceshipInfo{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceshipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceshipInfo) ProtoMessage() {}

func (x *SpaceshipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceshipInfo.ProtoReflect.Descriptor instead.
func (*SpaceshipInfo) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceshipInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceshipInfo) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *SpaceshipInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SpaceshipInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *SpaceshipInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SpaceshipUpdateInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Model         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer  *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Price         *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceshipUpdateInfo) Reset() {
	*x = SpaceshipUpdateInfo{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceshipUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceshipUpdateInfo) ProtoMessage() {}

func (x *SpaceshipUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceshipUpdateInfo.ProtoReflect.Descriptor instead.
func (*SpaceshipUpdateInfo) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceshipUpdateInfo) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SpaceshipUpdateInfo) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *SpaceshipUpdateInfo) GetModel() *wrapperspb.StringValue {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *SpaceshipUpdateInfo) GetManufacturer() *wrapperspb.StringValue {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *SpaceshipUpdateInfo) GetPrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Price
	}
	return nil
}

type Spaceship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Info          *SpaceshipInfo         `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spaceship) Reset() {
	*x = Spaceship{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spaceship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spaceship) ProtoMessage() {}

func (x *Spaceship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spaceship.ProtoReflect.Descriptor instead.
func (*Spaceship) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{2}
}

func (x *Spaceship) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Spaceship) GetInfo() *SpaceshipInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Spaceship) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Spaceship) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SpaceshipInfo         `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetInfo() *SpaceshipInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaceship     *Spaceship             `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaceship     *Spaceship             `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UpdateInfo    *SpaceshipUpdateInfo   `protobuf:"bytes,2,opt,name=update_info,json=updateInfo,proto3" json:"update_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetUpdateInfo() *SpaceshipUpdateInfo {
	if x != nil {
		return x.UpdateInfo
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaceship     *Spaceship             `protobuf:"bytes,1,opt,name=spaceship,proto3" json:"spaceship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResponse) GetSpaceship() *Spaceship {
	if x != nil {
		return x.Spaceship
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceship_v1_spaceship_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceship_v1_spaceship_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_proto_spaceship_v1_spaceship_proto protoreflect.FileDescriptor

const file_proto_spaceship_v1_spaceship_proto_rawDesc = "" +
	"\n" +
	"\"proto/spaceship/v1/spaceship.proto\x12\fspaceship.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb3\x01\n" +
	"\rSpaceshipInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\xb1\x02\n" +
	"\x13SpaceshipUpdateInfo\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05model\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05model\x12@\n" +
	"\fmanufacturer\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\fmanufacturer\x122\n" +
	"\x05price\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05price\"\xc6\x01\n" +
	"\tSpaceship\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12/\n" +
	"\x04info\x18\x02 \x01(\v2\x1b.spaceship.v1.SpaceshipInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\rCreateRequest\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.spaceship.v1.SpaceshipInfoR\x04info\"G\n" +
	"\x0eCreateResponse\x125\n" +
	"\tspaceship\x18\x01 \x01(\v2\x17.spaceship.v1.SpaceshipR\tspaceship\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"D\n" +
	"\vGetResponse\x125\n" +
	"\tspaceship\x18\x01 \x01(\v2\x17.spaceship.v1.SpaceshipR\tspaceship\"g\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12B\n" +
	"\vupdate_info\x18\x02 \x01(\v2!.spaceship.v1.SpaceshipUpdateInfoR\n" +
	"updateInfo\"G\n" +
	"\x0eUpdateResponse\x125\n" +
	"\tspaceship\x18\x01 \x01(\v2\x17.spaceship.v1.SpaceshipR\tspaceship\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid2\x99\x02\n" +
	"\x12SpaceshipServiceV1\x12C\n" +
	"\x06Create\x12\x1b.spaceship.v1.CreateRequest\x1a\x1c.spaceship.v1.CreateResponse\x12:\n" +
	"\x03Get\x12\x18.spaceship.v1.GetRequest\x1a\x19.spaceship.v1.GetResponse\x12C\n" +
	"\x06Update\x12\x1b.spaceship.v1.UpdateRequest\x1a\x1c.spaceship.v1.UpdateResponse\x12=\n" +
	"\x06Delete\x12\x1b.spaceship.v1.DeleteRequest\x1a\x16.google.protobuf.EmptyB3Z1grpc-practice/pkg/proto/spaceship/v1;spaceship_v1b\x06proto3"

var (
	file_proto_spaceship_v1_spaceship_proto_rawDescOnce sync.Once
	file_proto_spaceship_v1_spaceship_proto_rawDescData []byte
)

func file_proto_spaceship_v1_spaceship_proto_rawDescGZIP() []byte {
	file_proto_spaceship_v1_spaceship_proto_rawDescOnce.Do(func() {
		file_proto_spaceship_v1_spaceship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_spaceship_v1_spaceship_proto_rawDesc), len(file_proto_spaceship_v1_spaceship_proto_rawDesc)))
	})
	return file_proto_spaceship_v1_spaceship_proto_rawDescData
}

var file_proto_spaceship_v1_spaceship_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_spaceship_v1_spaceship_proto_goTypes = []any{
	(*SpaceshipInfo)(nil),          // 0: spaceship.v1.SpaceshipInfo
	(*SpaceshipUpdateInfo)(nil),    // 1: spaceship.v1.SpaceshipUpdateInfo
	(*Spaceship)(nil),              // 2: spaceship.v1.Spaceship
	(*CreateRequest)(nil),          // 3: spaceship.v1.CreateRequest
	(*CreateResponse)(nil),         // 4: spaceship.v1.CreateResponse
	(*GetRequest)(nil),             // 5: spaceship.v1.GetRequest
	(*GetResponse)(nil),            // 6: spaceship.v1.GetResponse
	(*UpdateRequest)(nil),          // 7: spaceship.v1.UpdateRequest
	(*UpdateResponse)(nil),         // 8: spaceship.v1.UpdateResponse
	(*DeleteRequest)(nil),          // 9: spaceship.v1.DeleteRequest
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.DoubleValue)(nil), // 11: google.protobuf.DoubleValue
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_proto_spaceship_v1_spaceship_proto_depIdxs = []int32{
	10, // 0: spaceship.v1.SpaceshipInfo.description:type_name -> google.protobuf.StringValue
	10, // 1: spaceship.v1.SpaceshipUpdateInfo.name:type_name -> google.protobuf.StringValue
	10, // 2: spaceship.v1.SpaceshipUpdateInfo.description:type_name -> google.protobuf.StringValue
	10, // 3: spaceship.v1.SpaceshipUpdateInfo.model:type_name -> google.protobuf.StringValue
	10, // 4: spaceship.v1.SpaceshipUpdateInfo.manufacturer:type_name -> google.protobuf.StringValue
	11, // 5: spaceship.v1.SpaceshipUpdateInfo.price:type_name -> google.protobuf.DoubleValue
	0,  // 6: spaceship.v1.Spaceship.info:type_name -> spaceship.v1.SpaceshipInfo
	12, // 7: spaceship.v1.Spaceship.created_at:type_name -> google.protobuf.Timestamp
	12, // 8: spaceship.v1.Spaceship.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: spaceship.v1.CreateRequest.info:type_name -> spaceship.v1.SpaceshipInfo
	2,  // 10: spaceship.v1.CreateResponse.spaceship:type_name -> spaceship.v1.Spaceship
	2,  // 11: spaceship.v1.GetResponse.spaceship:type_name -> spaceship.v1.Spaceship
	1,  // 12: spaceship.v1.UpdateRequest.update_info:type_name -> spaceship.v1.SpaceshipUpdateInfo
	2,  // 13: spaceship.v1.UpdateResponse.spaceship:type_name -> spaceship.v1.Spaceship
	3,  // 14: spaceship.v1.SpaceshipServiceV1.Create:input_type -> spaceship.v1.CreateRequest
	5,  // 15: spaceship.v1.SpaceshipServiceV1.Get:input_type -> spaceship.v1.GetRequest
	7,  // 16: spaceship.v1.SpaceshipServiceV1.Update:input_type -> spaceship.v1.UpdateRequest
	9,  // 17: spaceship.v1.SpaceshipServiceV1.Delete:input_type -> spaceship.v1.DeleteRequest
	4,  // 18: spaceship.v1.SpaceshipServiceV1.Create:output_type -> spaceship.v1.CreateResponse
	6,  // 19: spaceship.v1.SpaceshipServiceV1.Get:output_type -> spaceship.v1.GetResponse
	8,  // 20: spaceship.v1.SpaceshipServiceV1.Update:output_type -> spaceship.v1.UpdateResponse
	13, // 21: spaceship.v1.SpaceshipServiceV1.Delete:output_type -> google.protobuf.Empty
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_spaceship_v1_spaceship_proto_init() }
func file_proto_spaceship_v1_spaceship_proto_init() {
	if File_proto_spaceship_v1_spaceship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_spaceship_v1_spaceship_proto_rawDesc), len(file_proto_spaceship_v1_spaceship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spaceship_v1_spaceship_proto_goTypes,
		DependencyIndexes: file_proto_spaceship_v1_spaceship_proto_depIdxs,
		MessageInfos:      file_proto_spaceship_v1_spaceship_proto_msgTypes,
	}.Build()
	File_proto_spaceship_v1_spaceship_proto = out.File
	file_proto_spaceship_v1_spaceship_proto_goTypes = nil
	file_proto_spaceship_v1_spaceship_proto_depIdxs = nil
}
